version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Docker/dockerfile.rag
    image: "oysgemutshet/pingis-ai-app:latest"
    ports:
      - "5000:5000"
    environment:
      - QDRANT_URL=${QDRANT_URL}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QDRANT_COLLECTION=${QDRANT_COLLECTION}
      - LANGSMITH_TRACING=${LANGSMITH_TRACING}
      - LANGSMITH_ENDPOINT=${LANGSMITH_ENDPOINT}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - LANGSMITH_PROJECT=${LANGSMITH_PROJECT}
      #- CLIENT_ID=${CLIENT_ID}
      #- CLIENT_SECRET=${CLIENT_SECRET}
      - PYTHONPATH=/app/src
    volumes:
      - .:/app
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      retries: 3